name: munto_app
description: munto's a new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.6.0+63

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  autocomplete_textfield: ^1.7.3
  badges: ^1.1.3
  cached_network_image: ^2.3.2+1
  clipboard: ^0.1.2+8
  color_thief_flutter: ^1.0.2
  cupertino_icons: ^0.1.3
  dio: ^3.0.10
  dots_indicator: ^1.2.0
  encrypt: ^4.0.3
  firebase_messaging: ^7.0.3
  flash: ^1.3.1
  flutter_absolute_path: ^1.0.6
  kakao_flutter_sdk: ^0.5.2
  flutter_svg: ^0.19.0
  horizontal_data_table: ^1.0.6+3
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+1
  intl: ^0.16.1
  modal_bottom_sheet: ^0.2.2
  multi_image_picker: ^4.7.14
  provider: ^4.3.2+2
  rxdart: ^0.24.1
  shared_preferences: ^0.5.12+4
  string_validator: ^0.1.4
  transparent_image: ^1.0.0
  url_launcher: ^5.7.10
  sign_in_with_apple: ^2.5.4
  heic_to_jpg: ^0.1.2
  apple_sign_in: ^0.1.0
  flutter_secure_storage: ^3.3.5
  app_settings: ^4.0.4
  enum_to_string: ^1.0.13
  uuid: ^2.2.2
  connectivity: ^2.0.1
  flutter_native_image: ^0.0.5+3
  package_info: ^0.4.0+16
  flutter_html: ^0.11.1
  flutter_login_facebook: ^0.4.0+1
  bootpay_api: ^2.0.7
  requests : ^3.3.0
  amplitude_flutter: ^2.0.0
  event_bus: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following view.page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/mypage/
    - assets/questions/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: fonts/NotoSansKR-Regular.otf
        - asset: fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: fonts/NotoSansKR-Bold.otf
          weight: 700
    - family: AppleSDGothicNeo
      fonts:
        - asset: fonts/AppleSDGothicNeoL.ttf
        - asset: fonts/AppleSDGothicNeoM.ttf
          weight: 500
        - asset: fonts/AppleSDGothicNeoB.ttf
          weight: 700
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
